# from utils import generate_unique_ID
import uuid

microgreens_list = [
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Pea",
        "product_price": "7.50",
        "product_description": "Our micro peas are grown with the utmost care and experience. They exhibit a vibrant green hue, tender texture, decorative shape and an explosion of sweet, earthy flavor that will elevate any dish.",
        "prodcut_img": "Pea",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Sorrel",
        "product_price": "5.50",
        "product_description": "The sorrel we produce is meticulously cultivated and is an exotic and vibrant addition to elevate your cuisine, with light green leaves and red veins and a slightly acidic taste, this ingredient will elevate your dishes.",
        "prodcut_img": "Sorrel",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Amaranth",
        "product_price": "5.50",
        "product_description": "With a mild flavour reminiscent of red beet or spinach, this herb offers a delicious taste that beautifully complements a wide array of dishes.",
        "prodcut_img": "Amaranth",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Coriander",
        "product_price": "5.20",
        "product_description": "Our coriander is an aromatic and versatile option to enhance the flavour of your dishes. With subtle citrus notes and the characteristic aroma of coriander, this herb will transform your cooking.",
        "prodcut_img": "Coriander",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Thai Basil",
        "product_price": "5.50",
        "product_description": "Thai Basil is an aromatic herb that combines the classic freshness of basil with exotic notes of anise and clove.",
        "prodcut_img": "Thai_Basil",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Genovese Basil",
        "product_price": "5.50",
        "product_description": "Our basil is a bold and fresh herb with basil flavours and subtle clove notes. As the leaves are young, they can be used whole.",
        "prodcut_img": "Genovese_Basil",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Lemon Basil",
        "product_price": "5.50",
        "product_description": "A refreshing burst of lemon flavour with delicate notes of anise in this small herb that brings a new dimension to fish, shellfish, and scallop dishes, adding a citrusy and vibrant touch.",
        "prodcut_img": "Lemon_Basil",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Nasturtium",
        "product_price": "3.99",
        "product_description": "With its delicate lily pad-shaped leaves and vibrant colour, Nasturtium has a crunchy texture that hides a spicy and refreshing flavour, awakening your senses and making each bite an explosion of flavours.",
        "prodcut_img": "Nasturtium",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Huacatay",
        "product_price": "5.99",
        "product_description": "With vibrant green serrated leaves and a refreshing tropical aroma reminiscent of passion fruit or pineapple, our Huacatay offers a unique sensory experience.",
        "prodcut_img": "Huacatay",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Purple Basil",
        "product_price": "4.49",
        "product_description": "Purple Basil is a variant of classic basil that stands out for its vibrant colour and slightly spicy flavour, with sweet and herbal notes.",
        "prodcut_img": "Purple_Basil",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Lemon Zest",
        "product_price": "4.49",
        "product_description": "Lemon Zest is a herb with small, serrated leaves, featuring a vibrant green color and a slightly rough texture. Its leaves are narrow and elongated, with a fresh aroma and an intense citrus flavor reminiscent of lemon.",
        "prodcut_img": "Lemon_Zest",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Lemon Balm",
        "product_price": "4.50",
        "product_description": "Our Lemon Balm is a delightful aromatic combination of mint flavour and a hint of lemon, set to revolutionise your cooking.",
        "prodcut_img": "Lemon_Balm",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Arugula",
        "product_price": "8.89",
        "product_description": "Arugula our Micro Rocket, with young, slightly spicy leaves, has a distinctive nutty flavour and is perfect for adding a special touch to your recipes.",
        "prodcut_img": "Arugula",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Beetroot",
        "product_price": "6.20",
        "product_description": "Our Micro Beetroot is a versatile ingredient that will add a special touch to your dishes. With a light earthy aroma from the root, this plant is not only a visual delight. Its delicate green leaves and vibrant red stems can be used in both sweet and savoury dishes.",
        "prodcut_img": "Beetroot",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Parsley",
        "product_price": "6.30",
        "product_description": "Our Micro Parsley is small and delicate but big in its fresh, herbaceous flavour. Its bright green leaves are perfect for decorating and seasoning a variety of dishes - red meats, fish, and poultry.",
        "prodcut_img": "Parsley",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Leek",
        "product_price": "4.49",
        "product_description": "Leek, a versatile ingredient that adds a touch of mild and aromatic flavour to dishes. With a distinct appearance and a unique taste, this leek is a unique addition to your kitchen.",
        "prodcut_img": "Leek",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Chickpea",
        "product_price": "4.49",
        "product_description": "Chickpeas are an amazing ingredient, with a succulent texture and an authentic, slightly earthy flavour. Originating from young Cicer plants, known for producing chickpeas, they are a fantastic choice for those looking to add flavour and nutrition to their cuisine.",
        "prodcut_img": "Chickpea",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Pak Choi",
        "product_price": "5.50",
        "product_description": "Pak Choi is a versatile vegetable, it can be added to salads, soups, or served as a side for grilled meats and fish dishes.",
        "prodcut_img": "Pak_Choi",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Radish",
        "product_price": "5.50",
        "product_description": "Micro Watercress features small, delicate leaves with a vibrant green hue. It has a distinctive flavour, slightly bitter and acidic, with spicy notes that awaken the palate. Its small, serrated leaves make it perfect for garnishing dishes and adding a touch of freshness.",
        "prodcut_img": "Radish",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Watercress",
        "product_price": "5.50",
        "product_description": "Our Micro Red Mustard offers a mild mustard flavour with delicate notes of cauliflower and a vibrant colour that gives it a playful character. It pairs perfectly with robust meats and fish, as well as different types of cabbage and potatoes.",
        "prodcut_img": "Watercress",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Red Mustard",
        "product_price": "5.50",
        "product_description": "",
        "prodcut_img": "Red_Mustard",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Curry",
        "product_price": "5.50",
        "product_description": "Imagine a combination of celery with a hint of parsley, but on steroids, and you have our Micro Curry! With thin, elongated leaves of an intense green, this is not a shy microgreen at all.",
        "prodcut_img": "Curry",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Wheatgrass",
        "product_price": "5.50",
        "product_description": "With a strong and sweet flavor and thin, attractive green leaves, Wheatgrass stands out as a versatile option for adding color and nutrition to your refreshing juices, creative cocktails, morning shots, and desserts.",
        "prodcut_img": "Wheatgrass",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Green Shiso",
        "product_price": "5.50",
        "product_description": "Meet Green Shiso, a vibrant and flavourful herb that adds a special touch to a variety of dishes, from raw fish to fine cheeses. With an intense green hue, Green Shiso is a small leaf but packed with flavour.",
        "prodcut_img": "Green_Shiso",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Celery",
        "product_price": "5.50",
        "product_description": "Celery is a classic in the kitchen, perfectly suited to a wide variety of recipes. Known for its fresh herbal flavour with hints of nutmeg, citrus, and parsley, leaving a lasting bitter and spicy aftertaste on the palate.",
        "prodcut_img": "Celery",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Wasabi Mustard",
        "product_price": "5.50",
        "product_description": "Wasabi Mustard delivers a strong, nasal-spicy flavour similar to wasabi, making it ideal for fresh and intense dishes. This ingredient is perfect for those seeking bold and unique flavours.",
        "prodcut_img": "Wasabi_Mustard",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Chinese Mahogany",
        "product_price": "5.50",
        "product_description": "Chinese Mahogany is, in fact, an edible tree that offers a unique experience to the palate. Its small leaves display vibrant green tones, while its compact size hides a surprising flavor.",
        "prodcut_img": "Chinese_Mahogany",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Shiso",
        "product_price": "5.50",
        "product_description": "Shiso, widely used in Asian cuisine and particularly prominent in Japan, offers leaves with a complex flavour profile, blending notes of anise, lemon, and fresh herbs.",
        "prodcut_img": "Shiso",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Sunflower",
        "product_price": "5.50",
        "product_description": "Sunflower leaves are a light and healthy choice, with a fresh, nutty flavour reminiscent of walnuts. Crunchy and nutritious, they are rich in vitamins A and E, as well as minerals like magnesium and potassium.",
        "prodcut_img": "Sunflower",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Szechuan",
        "product_price": "5.50",
        "product_description": "Szechuan, known in Brazil as Jambu, is a unique plant native to the Amazon. Its leaves are renowned for their fresh and slightly spicy flavour, which provides a unique sensory experience due to the numbing effect they induce.",
        "prodcut_img": "Szechuan",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Purple Radish",
        "product_price": "5.50",
        "product_description": "Purple Radish is known for its deep and vibrant colour, which can give an impressive look to any dish. It offers a unique blend of spiciness and freshness, with distinct notes of radish and daikon, adding a surprising touch of flavour to a wide variety of dishes.",
        "prodcut_img": "Purple_Radish",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Giant Mustard",
        "product_price": "5.50",
        "product_description": "Discover Giant Mustard, a variety with an intense wasabi and mustard flavor. Its green leaves with purple veins give it a unique appearance and enhance the flavor of salads. It also pairs well with carpaccio or raw fish and adds a spicy touch to cold meat or fish dishes.",
        "prodcut_img": "Giant_Mustard",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Thyme",
        "product_price": "5.50",
        "product_description": "Thyme is an essential aromatic herb in the kitchen, with an intense herbal flavour and fresh notes that complement a wide range of dishes. It is perfect for seasoning meats, fish, soups, and marinades.",
        "prodcut_img": "Thyme",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Mizuna",
        "product_price": "5.50",
        "product_description": "Mizuna stands out for its mild flavour with a slight peppery touch and the crisp texture of its leaves. This vegetable is perfect for light and healthy dishes, adding freshness and balance to your recipes.",
        "prodcut_img": "Mizuna",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Micro Lavender",
        "product_price": "9.05",
        "product_description": "Our lavender is one of the many varieties of microgreens we produce all year round! Super aromatic, it has a peculiar strong and spicy flavor with warm notes. It's perfect for those looking to add an out-of-the-box touch to any dish or dessert.",
        "prodcut_img": "Micro_Lavender",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Red Cabbage",
        "product_price": "7.50",
        "product_description": "Red Cabbage is known for its intense, slightly bitter flavour and vibrant colour, making it an excellent choice for colourful and nutritious dishes. Its deep purple hue adds an impressive visual impact to your meals.",
        "prodcut_img": "Red_Cabbage",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Carrot",
        "product_price": "6.30",
        "product_description": "Carrot leaves are curly and delicate, with a fresh and slightly sweet flavour reminiscent of the root, complementing a variety of dishes. You can use them to make pestos, add freshness to salads, or decorate soups and garnishes.",
        "prodcut_img": "Carrot",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Borage",
        "product_price": "3.50",
        "product_description": "Borage is recognised for its delicate green leaves with a slight fuzz, offering a refreshing and mild flavour with notes reminiscent of oysters and cucumber. In terms of size, the leaves are small and easy to handle, making them ideal for any kitchen.",
        "prodcut_img": "Borage",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Clover",
        "product_price": "2.50",
        "product_description": "Clover is a delicate choice with a tangy, sour, and slightly herbal flavour, perfect for complementing a variety of dishes. Its elegant appearance makes it very easy to plate and an excellent finishing touch for salads, starters, snacks, and desserts.",
        "prodcut_img": "Clover",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "microgreens",
        "product_name": "Fennel",
        "product_price": "2.79",
        "product_description": "Fennel is renowned for its distinct aroma, with notes of anise that bring lightness and freshness to dishes. Rich in nutrients and fibre, it is an essential herb for those looking to balance flavour and health.",
        "prodcut_img": "Fennel",
    },
]


herbs_list = [
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "herbs",
        "product_name": "Oregano",
        "product_price": "3.39",
        "product_description": "With warm spicy leaves this is the perfect herb for pizzas, pasta, egg and cheese dishes. It grows into a hardy clump and the flowers are loved by bees in summer.",
        "prodcut_img": "Oregano",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "herbs",
        "product_name": "Mint",
        "product_price": "4.50",
        "product_description": "Like all mint varieties, peppermint is an excellent culinary herb used around the world in many dishes especially salads.",
        "prodcut_img": "Mint",
    },
    {
        "product_id": str(uuid.uuid4()),
        "product_category": "herbs",
        "product_name": "Rosmary",
        "product_price": "2.99",
        "product_description": "Rosemary is an aromatic evergreen shrub with leaves similar to hemlock needles.",
        "prodcut_img": "Rosmary",
    }
]
